project:
  type: website
  output-dir: docs
website:
  title: "Liam Cummins"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



