project:
  type: website
  output-dir: docs

website:
  title: "Liam Cummins"
  search: true
  navbar:
    logo: images\GT.PNG

    left:
      - href: index.qmd
        text: Home
        icon: house-door-fill
      - href: about.qmd
        text: About
      - href: hello.qmd
        text: Hello
      - href: projects.qmd
        text: Projects
     
    right:
      - icon: github
        href: https://github.com/Liam-Stack412/Liam-Stack412.github.io

format:
  html:
    theme: Cerulean
    css: styles.scss
    toc: true
    fontsize: 1.1em
    mainfont: Montserrat
