project:
  type: website
  output-dir: docs
website:
  title: "Liam Cummins"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hello.qmd

format:
  html:
    theme: 
    - Lux
    - Cerulean
    - brand
    css: styles.scss
    toc: true
    fontsize: 1.1em
    mainfont: montserrat

