project:
  type: website
  output-dir: docs
website:
  title: "Liam Cummins"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hello.qmd

format:
  html:
    theme: 
      - lux
      - Quartz
      - brand
    css: styles.css
    toc: true
    fontsize: 1.1em
  

